export const engineeringNotesB = [
  "Practical minimum chamber width often depends on pump base elbows or guide rail spacing.",
  "Concrete wall thickness is not added in this internal geometry calculator.",
  "Users should apply structural allowances externally.",
  "Access hatch size can influence the selected internal plan dimensions.",
  "For small stations, vendor package diameters may control the final circular size.",
  "For large stations, sump inlet arrangement can affect hydraulic performance strongly.",
  "Submersible pumps usually occupy the wet well itself.",
  "Dry-installed pumps are located in a dry pit or dry compartment adjacent to the wet side.",
  "That difference affects equipment arrangement but not the fundamental wet-side storage math.",
  "A common design sequence is pump selection first, storage sizing second, geometry third.",
  "If pump duty is changed, the active volume should be recalculated.",
  "If starts per hour is tightened, volume rises linearly under the V = TQ/4 rule.",
  "If safety factor rises, area and total volume rise proportionally.",
  "If effective depth rises, plan area reduces for the same active storage volume.",
  "However, greater depth may not always be hydraulically or operationally desirable.",
  "The calculator leaves those engineering judgments visible rather than hidden.",
  "Users can fix one rectangular side to suit parcel or precast constraints.",
  "The remaining side is then back-calculated from required area.",
  "When neither side is fixed, the chosen aspect ratio drives the economical suggestion.",
  "An aspect ratio of 1.2 to 2.0 is often used for practical rectangular basins.",
  "Very elongated shapes can complicate hydraulics and maintenance.",
  "Very compact square shapes may simplify some layouts but not all equipment spacing.",
  "The app therefore allows direct user control.",
  "Pump-down checks should be interpreted carefully under variable inflow.",
  "Real inflow is rarely constant in wastewater networks.",
  "This tool uses a steady inflow assumption for a transparent first-pass estimate.",
  "Check floating debris, ragging, and vortex control separately.",
  "Check inlet velocity and turbulence separately.",
  "Check emergency overflow and alarm settings separately.",
  "Check generator duty and failure scenarios separately.",
  "Check force main surge and check-valve behavior separately.",
  "A future export feature could generate a formatted calculation sheet.",
  "Another future option could store project metadata in local browser storage.",
  "A comparison chart could also be added without a backend.",
  "Because the app is modular, those features can be appended safely.",
  "The current theme intentionally uses bold gradients and glass panels for a catchier interface.",
  "Color contrast remains suitable for professional use.",
  "Print styling removes the hero banner for cleaner hardcopy output.",
  "Copy-to-clipboard output is plain text for easy emailing.",
  "This note bundle is preserved as standalone documentation content.",
  "It can later be surfaced in a Help modal if required.",
  "Nothing in this file changes the calculation engine.",
  "Its role is documentation and project volume distribution.",
  "The same approach is used in many static sites to keep modules focused.",
  "No external libraries are required anywhere in the app.",
  "The project is therefore easy to upload to GitHub Pages.",
  "This is the end of the secondary note block."
];
